#!/usr/bin/env php
<?php
ini_set("display_errors", 0);
error_reporting(-1);
register_shutdown_function(
    function(){
        $e = error_get_last();
        if( $e['type'] == E_ERROR ||
            $e['type'] == E_PARSE ||
            $e['type'] == E_CORE_ERROR ||
            $e['type'] == E_COMPILE_ERROR ||
            $e['type'] == E_USER_ERROR ){
            echo "FATAL ERROR:\n";
            echo "Error type:\t {$e['type']}\n";
            echo "Error message:\t {$e['message']}\n";
            echo "Error file:\t {$e['file']}\n";
            echo "Error line:\t {$e['line']}\n";
        }
    }
);
set_error_handler(function($errno, $errstr, $errfile, $errline){
    throw new ErrorException($errstr, $errno, 0, $errfile, $errline);
});

require 'vendor/autoload.php';

define('MAX_PRIV_KEY_FILE_SIZE', 10240); // 適当である
define('MAX_INPUT_FILE_SIZE', 1024); // 適当である

// Command Line option
$cmd = new \Commando\Command();
$cmd->option('k')
    ->aka('privkey')
    ->default(getenv('HOME').'/.ssh/id_rsa')
    ->must(function($key) {
        // file path
        if(file_exists($key)){
            return true;
        }
        return false;
    })
    ->describedAs("private key file.");

$cmd->option('i')
    ->aka('infile')
    ->describedAs('input encoded file');

$cmd->option('o')
    ->aka('outfile')
    ->describedAs('output decoded file');

$cmd->option('r')
    ->aka('raw')
    ->aka('binary')
    ->describedAs('Don\'t base64 decode ')
    ->boolean();

$cmd->option('i_want_set_pass_phrase_option_i_am_sane')
    ->describedAs('Private key pass phrase, DON\'T USE THIS, if you sane.');

// load key
if(!file_exists($cmd['k'])){
    die('require private key');
}

if(filesize($cmd['k'])>MAX_PRIV_KEY_FILE_SIZE){
    die('huge key file. really?');
}
$ssh_priv_key = file_get_contents($cmd['k']);

// get pass phrase
if(is_null($cmd['i_want_set_pass_phrase_option_i_am_sane'])){
    echo "please type pass phrase (or blank) :";
    system('stty -echo'); // disable local echo (hide input pass phrase)
    $pass_phrase = fgets(STDIN);
    $pass_phrase = rtrim($pass_phrase);
    system('stty echo'); // restore local echo
    echo "\n";
}else{
    $pass_phrase = $cmd['i_want_set_pass_phrase_option_i_am_sane'];
}

// load data
if($cmd['i']){
    if(!file_exists($cmd['i'])){
        die('input file not found.');
    }

    if(filesize($cmd['i'])>MAX_INPUT_FILE_SIZE){
        die('input file size too big.');
    }

    $data = file_get_contents($cmd['i']);
}else{
    if(is_null($cmd['i_want_set_pass_phrase_option_i_am_sane'])){
        echo "paste data and Enter,^D".PHP_EOL;
    }
    $data = file_get_contents('php://stdin');
}

// decode base64.
if(!$cmd['r']){
    $data = base64_decode($data);
}

try{
    $plain = \Uzulla\Crypt\Misc::decodeBySshPrivKey($ssh_priv_key, $pass_phrase, $data);
}catch(\Exception $e){
    die("decode fail. : ".$e->getMessage().PHP_EOL);
}
unset($pass_phrase);

// Output
if($cmd['o']){
    file_put_contents($cmd['o'], $plain);
}else{
    echo $plain.PHP_EOL;
}


